### PR TITLE
MySQL Aggregrate function (AVG, SUM, COUNT, MAX, MIN, DISTINCT) (#648)

### PR DESCRIPTION
**Pull request by tonny-sofijan**
Adding MySQL Aggregrate function (AVG, SUM, COUNT, MAX, MIN, DISTINCT) (#648)
code that changed is in line: 2354-2418

### CODE REVIEW

**Comment by avbdr** [comment]
you patch is not based on master.

**Comment by tonny-sofijan** [comment]
I've been copy-paste from MysqliDb.php master, add my code, forking, upload to my fork code, and request pull. If there's still difference with the master, I give up.

**Comment by avbdr** [comment]
:) ok. ill do it myself

**Comment by tonny-sofijan** [comment]
@avbdr thanks.

**Comment by duhow** [comment]
Made a PR: https://github.com/joshcam/PHP-MySQLi-Database-Class/pull/669

**Pull request closed without merging**
