### PR TITLE
Fixed byId and provide pagination with data type

### PR DESCRIPTION
**Pull request by Tom29**
- Fixed using [byId](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/568) error in active record pattern 
- Provide [pagination with data type](https://github.com/joshcam/PHP-MySQLi-Database-Class/issues/561) (object, array, json)

### CODE REVIEW

**Comment by avbdr** [comment]
have you checked if tests are passing?

**Comment by Tom29** [comment]
I've checked on your tests, and it's a mess.
DB files in dataimport doesn't match with model, path, everything ...
I've tested on my project and it works. I didn't change much, you can see in the code.

**Comment by avbdr** [comment]
its not a mess, you need to create database and then run mysqliDbTests.php and after dbObjectTests.php

**Comment by Tom29** [comment]
Then how do i know it passes?
I've done all two files, mysqliDbTests.php return the list of queries. dbObjectTests.php return this line:

`Multisave problem {"customerId":2,"userId":{"login":"testuser","firstName":"john","lastName":"Doe Jr","createdAt":"2016-12-20 18:44:55","id":false},"productName":"product6","id":6}`

Same result with `master` and mine

**Comment by avbdr** [comment]
both test scripts should return 'All done'

**Comment by Tom29** [comment]
All done Memory usage: 973424 with `mysqliDbTests.php`
And you should check your `master`, because `dbObjectTests.php` returns the result above.

**Comment by avbdr** [comment]
</pre></pre>All done
Memory usage: 879040
avb@ds:~/work/PHP-MySQLi-Database-Class/tests$ php mysqliDbTests.php ^C
avb@ds:~/work/PHP-MySQLi-Database-Class/tests$ php dbObjectTests.php 
All done

**Comment by avbdr** [comment]
i have applied you patch and executed tests. seems working :) Thanks

**Pull request merged**
