### PR TITLE
LOCK IN SHARE MODE & FOR UPDATE Correction

### PR DESCRIPTION
**Pull request by rajjanorkar**
LOCK IN SHARE MODE & FOR UPDATE correction.

### CODE REVIEW

**Comment by avbdr** [comment]
i have keep them as is to keep compatibility with MYSQL standart terms. I dont think we want to invent our own keywords.

**Comment by rajjanorkar** [comment]
hi @avbdr 

Please check your logic.

           else if ($option == 'MYSQLI_FOR_UPDATE')
                $this->_forUpdate = true;
           else if ($option == 'MYSQLI_LOCK_IN_SHARE_MODE')
                $this->_lockInShareMode = true;

**Comment by avbdr** [comment]
thank you. :) fixed

**Comment by rajjanorkar** [comment]
Great...

**Pull request closed without merging**
