### PR TITLE
Updated MysqliDb.php

### PR DESCRIPTION
**Pull request by afilini**
* Added backticks around $tableName in every query to avoid error (http://stackoverflow.com/questions/1962859/importance-of-backtick-around-table-name-in-mysql-query)
* Added a space after $tableName in insert into query to avoid problem in some cases

### CODE REVIEW

**Comment by sanderploegsma** [comment]
Was about to open this exact PR, glad to see I'm not the only one with this issue. Wonder why it's still not merged @joshcam?

**Comment by avbdr** [comment]
1. adding backticks to select will break calls like  update/get("users u, products p") and bunch of others. 
2. adding backticks to table names wont help much as where conditions still wont be escaped.
3. it is not clear how to handle weird fields/table names like `my table` or `my,table` in automatic way. 

3) completely ruins my enthusiasm on writting a fix for this issue as anyway it will be solving 'half of the problem'.



I have some ideas but its pretty tricky change and

**Comment by sanderploegsma** [comment]
I'm actually not having any issues with the current version of the class when using reserved words like `key` as column names, except for when using `$db->orderBy()` since the regexp in that function filters backticks, so using ``$db->orderBy('`key`')`` will not work. 

Not sure why backticks aren't allowed in column names for this particular function, but adding them to the expression seems to fix my issue without causing any huge problems so far.

**Comment by avbdr** [comment]
not sure how I overlooked that. 
I just pushed a fix to https://github.com/avbdr/PHP-MySQLi-Database-Class.git
please check and let me know. That should be merged into master soon.

**Pull request closed without merging**
