### PR TITLE
Changed inc() and dec() methods to support float

### PR DESCRIPTION
**Pull request by Luke-j**
It's valid to increment a field by a float, this allows both ints and floats to be used in increments and decrements, while still keeping the default (int)1.

### CODE REVIEW

**Comment by avbdr** [comment]
patch looks valid except that I would like to add is_numeric() validation as we are removing int cast.Can you fix and send?
thanks

**Comment by Luke-j** [comment]
Sure thing! Changed to an error when an invalid argument is supplied, checked with is_number().

**Comment by avbdr** [comment]
thanks. commited.

**Comment by Luke-j** [comment]
Thanks :)

**Pull request merged**
