### PR TITLE
Adding support for mysql error codes

### PR DESCRIPTION
**Pull request by Ettemlevest**
#437

### CODE REVIEW

**Comment by avbdr** [comment]
can you please update readme as well? thank you

**Comment by Ettemlevest** [comment]
Thanks for the reminder. I added a small description to the readme.

**Comment by avbdr** [comment]
as well, I noticed you are not cleaning up errno variable in reset() function. Its getting called after each query execution to remove all the data

**Comment by Ettemlevest** [comment]
I just added the errno parts after every $_stmtError lines but I did not check to reset the values. In this case we should also reset the $_stmtError string.

**Comment by avbdr** [comment]
sorry, my bad, this variables shouldnt be reset :) as you are using them after execution
fine. ill land this as is

**Pull request merged**
