### PR TITLE
suppress warnings on PHP7.0.4

### PR DESCRIPTION
**Pull request by cord**
even with exception handling warnings were displayed on PHP7.0.4

### CODE REVIEW

**Comment by avbdr** [comment]
can you please clarify which warnings you are fixing? 
I have executed tests/* files under 7.0.14 and do not see any warnings

**Comment by cord** [comment]
thanks for checking: in context of a store system warnings for failed connections (invalid credentials) where shown before the exception was triggered. Probably this is depending on the error reporting settings in the store system.

**Comment by avbdr** [comment]
i have E_ALL set :)

**Comment by cord** [comment]
Actually I do not understand why the errors from `new mysqli()` where shown but they did and the changes fixed that issue ..?

**Pull request closed without merging**
