### PR TITLE
PDO Implementation + Stored Procedures ( Ready to pay )

### PR DESCRIPTION
**Pull request by pratikghela**
Guys, 

We are developing a web app and are using mySQL as our current DBMS. We are not sure about continuing the use of mysql and feel that we may change the DBMS to MSSQL going ahead. We need our system to be DB independent and PDO seems like an amazing way to do this. I am in love with mySQLI DB Class and want the same functions and stuff to be used . Our only requirement is to create a class similar to this with same functions and use PDO and add support for Stored Procedures. 

We have a budget of $500 for this. 

Anyone interested can reply me. 

Thanks!

### CODE REVIEW

**Comment by avbdr** [comment]
stored procedures support is already implemented. 
Id say we could implement nonmysql connections via db but I would double that budget for this. 
On unrelated to moneys question, i pretty much sure that mysql->mssql switch wont be seamless as ms sql have lot of differences.

**Comment by pratikghela** [comment]
Can you please let me know the budget for PDO support. I would like to implement PDO as PDO supports MSSQL. We want PDO support from the start as we do not want to change the entire application and want an ability to implement a plug & play system where we can just change the database quickly without major downtime and code restructuring.

**Comment by avbdr** [comment]
please add me on skype smarttechdo

**Comment by avbdr** [comment]
budget for this project would be 1000$

**Comment by tommyknocker** [comment]
I can do it (implement PDO support for MysqliDb class) for $500 and for one week. Feel free to contact me by mail me[dog]mysrv.ru or by skype - dr_manson.

**Pull request closed without merging**
