### PR TITLE
Adding error number to exception

### PR DESCRIPTION
**Pull request by Ettemlevest**
Adding mysqli error number to throwed exception in _prepareQuery() method.

### CODE REVIEW

**Comment by avbdr** [comment]
I like an idea, but can you add numbers to the rest of exceptions?

**Comment by Ettemlevest** [comment]
Added more error numbers to exceptions. There are 16 exception throws but not all can have mysql error number. Like the exceptions thrown in inc() or dec() methods.

Hope I didn't left out any important part.

**Comment by avbdr** [comment]
nice, thank you

**Comment by avbdr** [comment]
can you please update readme as well? :)

**Pull request merged**
