### PR TITLE
Added methods for importing data (CSV, XML) and table locking

### PR DESCRIPTION
**Pull request by Noneatme**

### CODE REVIEW

**Comment by avbdr** [comment]
very nice patch. Thank you. Ill send me code comments a  bit later for you to adjust and we are ready to land

**Comment by Noneatme** [comment]
Alright! Thanks!

**Comment by avbdr** [comment]
Sorry, it took me longer :) Patch looks great except couple issues:
1. default settings validation: You can create an array of default values and then do an array_merge with settings passed into the function.
2. revert if(file_exists($importFile))  to an early return to streamline the code. 
```
if (!file_exists) {
     throw exception
     return
}
```

3. 
```
		if($result) {
				$success = true;
			}
			// Something went wrong
			else {
				$success = false; 
			}
```

this is the same as return $result;

4. rename loadXML -> loadXml  for a naming consistency.

**Comment by avbdr** [comment]
as well i think it doesnt make sense to add escapeQuery parameter as most of escaped sql queries will fail. You need to escape variables, not SQL query itself. 
So you can remove that.

**Comment by Noneatme** [comment]
I fixed the issues you you mentioned. Thanks!
But now, the tests fail somehow (data doesn't get inserted). I have to take a deeper look. Don't merge right now, I will push a commit later when I found the issue.

**Comment by Noneatme** [comment]
It should work now. The .csv test file was not in dos mode so the \r\n selector failed.

**Comment by avbdr** [comment]
thank you, merged

**Pull request merged**
