### PR TITLE
Implement support for HAVING

### PR DESCRIPTION
**Pull request by looki**
I implemented support for the HAVING operator. The interface is exactly the same as for WHERE, and the _buildWhere function was replaced by a more general one that works for both of them.

### CODE REVIEW

**Comment by avbdr** [comment]
great! Can you please add couple lines to a readme and also a test? Apart of this patch looks great

**Comment by looki** [comment]
Sure, I'll do that next week or so.

**Comment by tomitomas** [comment]
Nice feature !! :1:

**Comment by looki** [comment]
Sorry the delay on the patch, I haven't been working on this at all, but I'll get to it.

**Comment by avbdr** [comment]
commited to master with minor adjustments. thank you.

**Pull request closed without merging**
